"use client";

import { useEffect, useRef, useState } from "react";

type Lang = "es" | "en";
type Copy = { es: string; en: string };
const t = (copy: Copy, lang: Lang) => copy[lang];
const local = (value: string | Copy, lang: Lang) => typeof value === "string" ? value : value[lang];

const flow = [
  { code:"FRICTION", number:"01", title:{es:"Discernir para decidir",en:"Discern to decide"}, body:{es:"Detectar dónde está la fricción real. Distinguir entre ruido y señal. Identificar qué configuraciones generan resistencia.",en:"Detect where the real friction lives. Distinguish noise from signal. Identify which configurations generate resistance."}},
  { code:"LEAD", number:"02", title:{es:"Observar para orientar",en:"Observe to orient"}, body:{es:"Identificar los patrones invisibles que operan en el sistema. Ver lo que frena antes de proponer lo que mueve.",en:"Identify the invisible patterns operating within the system. See what holds it back before proposing what moves it."}},
  { code:"OWNERSHIP", number:"03", title:{es:"Elegir para construir",en:"Choose to build"}, body:{es:"Recuperar agencia sobre el sistema. Definir sobre qué se puede actuar realmente y desde ahí construir.",en:"Recover agency over the system. Define what can actually be acted upon, and build from there."}},
  { code:"WISDOM", number:"04", title:{es:"Comprender para responder",en:"Understand to respond"}, body:{es:"Integrar la información del sistema. Reconocer qué intervención corresponde. No toda fricción requiere la misma respuesta.",en:"Integrate the system's information. Recognize which intervention fits. Not every friction calls for the same response."}},
];

const profileMetrics = [
  {n:"18+",label:{es:"Años de trayectoria",en:"Years of experience"},title:{es:"Transformación a través de sistemas",en:"Transformation through systems"},detail:{es:"18+ años diseñando y reconfigurando sistemas, procesos y capacidades en organizaciones públicas y privadas, con casi una década principalmente en tecnología y transformación digital.",en:"18+ years designing and reconfiguring systems, processes and capabilities across public and private organizations, with nearly a decade focused primarily on technology and digital transformation."},toolkit:{es:["Systems Architecture","Change Management","Digital Transformation","Process Reengineering"],en:["Systems Architecture","Change Management","Digital Transformation","Process Reengineering"]}},
  {n:"1.000+",label:{es:"Procesos / trámites transformados",en:"Processes / procedures transformed"},title:{es:"Transformación & Digitalización",en:"Transformation & Digitalization"},detail:{es:"300+ nuevos procesos y trámites diseñados y 700+ optimizados o digitalizados, conectando operación, información, tecnología y adopción para transformar cómo funciona el sistema.",en:"300+ new processes and procedures designed and 700+ optimized or digitalized, connecting operations, information, technology and adoption to transform how the system works."},toolkit:{es:["Process Reengineering","Digitalization","Functional Analysis","Change Adoption"],en:["Process Reengineering","Digitalization","Functional Analysis","Change Adoption"]}},
  {n:"25+",label:{es:"Iniciativas tech",en:"Tech initiatives"},title:{es:"Delivery E2E & Operaciones",en:"E2E Delivery & Operations"},detail:{es:"Liderazgo de 25+ iniciativas tecnológicas, portfolios de 10+ proyectos/clientes simultáneos, 5 proveedores + desarrollo interno y articulación con 40+ stakeholders.",en:"Leadership of 25+ technology initiatives, portfolios of 10+ simultaneous projects/clients, 5 vendors plus in-house development, and alignment with 40+ stakeholders."},toolkit:{es:["IT Delivery","E2E Delivery","Operations","Vendor Management"],en:["IT Delivery","E2E Delivery","Operations","Vendor Management"]}},
  {n:"30+",label:{es:"Profesionales liderados",en:"Professionals led"},title:{es:"Liderazgo & Capability Building",en:"Leadership & Capability Building"},detail:{es:"Liderazgo de 30+ profesionales QA/testing y desarrollo de 5 líderes desde roles técnicos para operar células con autonomía, dentro de una configuración de 7 células dinámicas.",en:"Leadership of 30+ QA/testing professionals and development of 5 leaders from technical roles to operate autonomous cells, within a configuration of 7 dynamic cells."},toolkit:{es:["Capability Building","Leadership Development","Team Autonomy","Agile"],en:["Capability Building","Leadership Development","Team Autonomy","Agile"]}},
  {n:"3",label:{es:"Soluciones AI en producción",en:"AI solutions in production"},title:{es:"Applied AI & Automation",en:"Applied AI & Automation"},detail:{es:"Soluciones de IA y automatización diseñadas e implementadas E2E, con 3 actualmente en producción, e IA/agentes aplicados también a delivery, seguimiento y operación.",en:"AI and automation solutions designed and implemented end-to-end, with 3 currently in production, and AI/agents also applied to delivery, tracking and operations."},toolkit:{es:["Applied AI","AI Agents","Automation","E2E Implementation"],en:["Applied AI","AI Agents","Automation","E2E Implementation"]}},
  {n:"2°",label:{es:"Premio AI Weekend 2026",en:"AI Weekend 2026 award"},title:{es:"SkillPath Flow · Innovación aplicada",en:"SkillPath Flow · Applied innovation"},detail:{es:"Co-creación y liderazgo conceptual/funcional de SkillPath Flow, plataforma gamificada con IA reconocida con el 2° Premio en AI Weekend San Rafael 2026.",en:"Co-creation and conceptual/functional leadership of SkillPath Flow, a gamified AI platform recognized with 2nd Prize at AI Weekend San Rafael 2026."},toolkit:{es:["Product Design","Applied AI","Gamification","Functional Architecture"],en:["Product Design","Applied AI","Gamification","Functional Architecture"]}},
];

const groups: any[] = [
  { title:"MPA Flow", label:{es:"Productos propios · Proyectos en curso",en:"Original products · Work in progress"}, projects:[
    {title:"SkillPath Flow",featured:true,spotlight:true,tagline:{es:"Talento evaluado por comportamiento real",en:"Talent assessed through real behavior"},body:{es:"Plataforma AI-powered de descubrimiento de talento. Perfiles basados en decisiones reales, no declaraciones. Sistema de niveles, XP y readiness.",en:"AI-powered talent discovery platform. Profiles based on real decisions, not declarations. Levels, XP and readiness system."},badge:{es:"2do lugar — Hackathon IA UTN, abril 2026",en:"2nd place — UTN AI Hackathon, April 2026"},image:"/skillpath-flow-journey-v11.png",url:"https://skillpathflow.com"},
    {title:{es:"Portal de Experiencias",en:"Experience Portal"},featured:true,tagline:{es:"Metodologías, contenidos y comunidad convertidos en una experiencia interactiva",en:"Methods, content and community turned into an interactive experience"},body:{es:"Sistema custom y adaptable para programas de formación, coaching, consultoría, membresías y comunidades. Integra contenidos, sesiones, herramientas, progreso, reflexiones, recursos y acompañamiento dentro de un recorrido digital con identidad propia.",en:"A custom, adaptable system for training, coaching, consulting, membership programs and communities. It brings content, sessions, tools, progress, reflections, resources and support into one branded digital journey."},badge:{es:"Arquitectura de Sistemas Custom · Prototipo",en:"Custom Systems Architecture · Prototype"},image:"/portal-experiencias-anonimo-v16.png",status:{es:"Vista anonimizada",en:"Anonymized preview"}},
    {title:{es:"Sistema de onboarding operativo",en:"Operational onboarding system"},tagline:{es:"Procesos, entrenamiento y autonomía para equipos comerciales",en:"Processes, enablement and autonomy for sales teams"},body:{es:"Dispositivo de onboarding que centraliza el flujo completo de captación, precomercialización y venta, junto con procesos documentados, preguntas frecuentes y tareas por rol. Permite que cada productor comprenda cómo operar y avance con autonomía, sin depender permanentemente del dueño o director de la inmobiliaria.",en:"An onboarding system that centralizes the full acquisition, pre-market and sales flow, together with documented processes, FAQs and role-based tasks. It enables each producer to understand how to operate and move forward autonomously, without constantly depending on the real-estate owner or director."},image:"/proceso-operativo-v16.png",status:{es:"Vista del proceso",en:"Process preview"}},
    {title:{es:"Dashboard de transformación operativa",en:"Operational transformation dashboard"},featured:true,tagline:{es:"Estrategia, brechas, métricas y evolución en una sola arquitectura",en:"Strategy, gaps, metrics and evolution in one architecture"},body:{es:"Tablero para convertir un diagnóstico operativo en un sistema de transformación trazable: estado del proyecto, tres horizontes de evolución, brechas críticas, proceso de venta, KPIs y cronograma.",en:"A dashboard that turns an operational diagnosis into a traceable transformation system: project status, three evolution horizons, critical gaps, sales process, KPIs and roadmap."},image:"/dashboard-transformacion-v16.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
    {title:"ScrumFlix MPA",tagline:{es:"Entrenamiento PSM I gamificado",en:"Gamified PSM I training"},body:{es:"Plataforma jugable de entrenamiento para certificación Scrum. Integra modos de dificultad, niveles progresivos, feedback contextual, diagnóstico de readiness, retrospectiva y microplan de refuerzo adaptativo.",en:"A game-based Scrum certification training platform. It integrates difficulty modes, progressive levels, contextual feedback, readiness diagnostics, retrospectives and an adaptive reinforcement micro-plan."},images:["/scrumflix-question-feedback.png","/scrumflix-retrospective.png"],status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"PSM I Trainer",tagline:{es:"Entrenamiento profundo para PSM I",en:"Deep training for PSM I"},body:{es:"5 niveles progresivos, dailys vivenciales, retros y refuerzo inteligente por concepto. La identidad azul pertenece a este entrenador, no a ScrumFlix.",en:"Five progressive levels, experiential dailies, retros and smart concept-based reinforcement. The blue identity belongs to this trainer, not ScrumFlix."},image:"/psm-trainer-daily-v16.png",status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"Trader Quest",tagline:{es:"Entrenamiento de trading gamificado",en:"Gamified trading training"},body:{es:"Dojo personal para desarrollar criterio real como trader. Combina microaprendizaje visual, desafíos progresivos, feedback experto, XP, rachas y progreso guardado automáticamente.",en:"A personal dojo for developing real trading judgment. It combines visual microlearning, progressive challenges, expert feedback, XP, streaks and automatically saved progress."},images:["/trader-quest-feedback.png","/trader-quest-candlestick.png"],status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:{es:"Radar de Agencia",en:"Agency Radar"},featured:true,tagline:{es:"Hacer visible dónde se concentra —y dónde se fuga— la capacidad de actuar",en:"Making visible where the capacity to act gathers—and where it leaks"},body:{es:"Experiencia interactiva para reconocer fugas de atención, leer la configuración actual y distinguir qué puede avanzar, qué necesita condiciones y qué requiere intervención. Convierte situaciones cotidianas en un mapa visual de presencia y agencia para ensayar decisiones más conscientes.",en:"An interactive experience for recognizing attention leaks, reading the current configuration and distinguishing what can move forward, what needs enabling conditions and what requires intervention. It turns everyday situations into a visual map of presence and agency for testing more conscious decisions."},images:["/egosumrc-attention.png","/egosumrc-configuration.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
    {title:"Código Soma: Alimentorum",featured:true,tagline:{es:"Registro, observación y experimentación convertidos en un sistema personal",en:"Tracking, observation and experimentation turned into a personal system"},body:{es:"Plataforma de autoobservación para registrar experiencias de alimentación, construir una bitácora y explorar correspondencias a lo largo del tiempo. Integra registro guiado, calendario, laboratorio, hipótesis de configuración y exportación para transformar datos cotidianos en aprendizaje personal, sin convertirlos en diagnósticos ni metas rígidas.",en:"A self-observation platform for recording food-related experiences, building a log and exploring correspondences over time. It integrates guided tracking, calendar, laboratory, configuration hypotheses and export tools to turn everyday data into personal learning—without turning it into diagnosis or rigid goals."},images:["/alimentorum-guided-log-clean.png","/alimentorum-lab-clean.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
    {title:"Código Leo",featured:true,tagline:{es:"Diseño y arquitectura de esencia de marca",en:"Brand Essence Design & Architecture"},body:{es:"App de lectura generativa estratégica para descubrir y diseñar la huella distintiva de una marca emprendedora: aquello singular que orienta su identidad, posicionamiento, narrativa y decisiones. Código Leo toma el signo de Leo como código simbólico de identidad, expresión y presencia propia. Va más allá del branding visual y traduce esa esencia en una configuración coherente del proyecto mediante un recorrido de triangulación, indagación y reconfiguración.",en:"A strategic generative-reading app for discovering and designing the distinctive imprint of an entrepreneurial brand: the singular core that guides its identity, positioning, narrative and decisions. Código Leo draws on the Leo sign as a symbolic code for identity, expression and distinctive presence. It goes beyond visual branding, translating that essence into a coherent project configuration through triangulation, inquiry and reconfiguration."},images:["/codigo-leo-entry.png","/codigo-leo-flow.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
  ]},
  { title:{es:"Productos y experiencias digitales",en:"Digital products & experiences"}, label:{es:"Arquitectura de producto · Casos anonimizados",en:"Product architecture · Anonymized cases"}, projects:[
    {title:"Growth Clarity Finder",tagline:{es:"Una experiencia digital que amplía y posiciona la propuesta de valor de un libro",en:"A digital experience that extends and positions a book's value proposition"},body:{es:"Producto digital diseñado para que un libro deje de ser una pieza estática y se convierta en la puerta de entrada a una experiencia interactiva. Traduce sus ideas en un recorrido de diagnóstico, reflexión y acción que ayuda a posicionar la obra, profundizar su propuesta de valor y extender el vínculo con sus lectores.",en:"A digital product designed to turn a book from a static asset into the entry point to an interactive experience. It translates the book's ideas into a journey of diagnosis, reflection and action that helps position the work, deepen its value proposition and extend the relationship with its readers."},image:"/growth-clarity-anonimo-v16.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
    {title:{es:"Atlas Sistémico Organizacional",en:"Organizational System Atlas"},tagline:{es:"Hacer visible qué existe, qué falta y qué sostiene cada parte del sistema",en:"Making visible what exists, what is missing and what supports each part of the system"},body:{es:"Producto digital para mapear personas, recursos, reuniones, preguntas, iniciativas y dependencias. Convierte información dispersa en una arquitectura operativa navegable y exportable.",en:"A digital product for mapping people, resources, meetings, questions, initiatives and dependencies. It turns scattered information into a navigable and exportable operating architecture."},image:"/system-atlas-anonymized.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
  ]},
  { title:{es:"Experiencias narrativas",en:"Narrative experiences"}, label:"MPA Universe · Stray Sheep", projects:[
    {title:{es:"Portales de Integración — Universo ¡Qué Embole!",en:"Integration Portals — ¡Qué Embole! Universe"},tagline:{es:"La lectura no termina en la página: continúa como experiencia",en:"The reading does not end on the page: it continues as an experience"},body:{es:"Sistema narrativo interactivo que conecta el libro físico con tres recorridos digitales desbloqueables. Códigos de acceso, contenido condicionado, personajes, pruebas y distintas etapas de integración convierten la obra en una experiencia transmedia.",en:"An interactive narrative system connecting the physical book with three unlockable digital journeys. Access codes, conditional content, characters, challenges and progressive integration stages turn the work into a transmedia experience."},mockup:"narrative-portal",status:{es:"Acceso protegido · Se muestran solo capturas",en:"Protected access · Screenshots only"}},
    {title:"De las Patrañas",tagline:{es:"Tres puertas. Tres formas de mirar la bola.",en:"Three doors. Three ways to look at the ball."},body:{es:"Portal de integración de la segunda parte del libro. Detectá las patrañas del sistema.",en:"Integration portal for the second part of the book. Spot the system's patrañas."},status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"Nigredo Ludus",tagline:{es:"El detector de Nigredo — ¿en qué etapa del proceso estás?",en:"The Nigredo detector — what stage of the process are you in?"},body:{es:"Herramienta simbólica de detección.",en:"Symbolic detection tool."},status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:{es:"Reto de Iniciación",en:"Initiation Challenge"},tagline:{es:"Tres señales. Una llave. Un umbral.",en:"Three signs. One key. One threshold."},body:{es:"Experiencia de acceso condicional al universo MPA.",en:"A conditional-access experience into the MPA universe."},status:{es:"Experiencia protegida",en:"Protected experience"}},
  ]},
  { title:{es:"Herramientas propias",en:"Own tools"}, label:"MPA Tools", projects:[
    {title:"DIMA — Conjuratio Dominus",tagline:{es:"No busques una definición. Buscá una revelación.",en:"Don't look for a definition. Look for a revelation."},body:{es:"Decodificación simbólica, tres modos de análisis y modelo freemium.",en:"Symbolic decoding, three analysis modes and a freemium model."},url:"https://dima-pi.vercel.app"},
  ]},
];

function FlowField(){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=ref.current;if(!canvas)return;
    const ctx=canvas.getContext("2d");if(!ctx)return;
    const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const particles=Array.from({length:72},()=>({p:Math.random(),speed:.0007+Math.random()*.0015,segment:Math.floor(Math.random()*4),size:.7+Math.random()*1.8,gold:Math.random()<.18}));
    let frame=0,raf=0,w=0,h=0;
    const resize=()=>{const box=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);w=box.width;h=box.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};
    const point=(a:{x:number;y:number},b:{x:number;y:number},p:number,cx:number,cy:number)=>{const c1={x:cx+(a.x-cx)*.2,y:cy+(a.y-cy)*.2};const c2={x:cx+(b.x-cx)*.2,y:cy+(b.y-cy)*.2};const q0={x:a.x+(c1.x-a.x)*p,y:a.y+(c1.y-a.y)*p};const q1={x:c1.x+(cx-c1.x)*p,y:c1.y+(cy-c1.y)*p};const q2={x:cx+(c2.x-cx)*p,y:cy+(c2.y-cy)*p};const r0={x:q0.x+(q1.x-q0.x)*p,y:q0.y+(q1.y-q0.y)*p};const r1={x:q1.x+(q2.x-q1.x)*p,y:q1.y+(q2.y-q1.y)*p};return{x:r0.x+(r1.x-r0.x)*p,y:r0.y+(r1.y-r0.y)*p}};
    const draw=()=>{ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,rx=Math.min(w*.42,520),ry=Math.min(h*.42,360);const nodes=[{x:cx,y:cy-ry},{x:cx+rx,y:cy},{x:cx,y:cy+ry},{x:cx-rx,y:cy}];
      for(let i=0;i<4;i++){const a=nodes[i],b=nodes[(i+1)%4];const c1x=cx+(a.x-cx)*.2,c1y=cy+(a.y-cy)*.2,c2x=cx+(b.x-cx)*.2,c2y=cy+(b.y-cy)*.2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo(c1x,c1y,c2x,c2y,b.x,b.y);ctx.strokeStyle="rgba(196,90,211,.18)";ctx.lineWidth=12;ctx.stroke();ctx.strokeStyle="rgba(208,96,217,.42)";ctx.lineWidth=2;ctx.stroke()}
      particles.forEach(p=>{if(!reduced){p.p+=p.speed;if(p.p>1){p.p=0;p.segment=(p.segment+1)%4}}const pos=point(nodes[p.segment],nodes[(p.segment+1)%4],p.p,cx,cy);ctx.beginPath();ctx.arc(pos.x,pos.y,p.size,0,Math.PI*2);ctx.fillStyle=p.gold?"rgba(201,163,110,.8)":"rgba(234,164,240,.72)";ctx.fill()});
      const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.min(w,h)*.25);glow.addColorStop(0,"rgba(208,96,217,.24)");glow.addColorStop(1,"rgba(156,77,255,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,Math.min(w,h)*.25,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(cx,cy);ctx.rotate(frame*.002);ctx.setLineDash([18,12]);ctx.strokeStyle="rgba(201,163,110,.28)";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,Math.min(w,h)*.12,0,Math.PI*2);ctx.stroke();ctx.restore();frame++;if(!reduced)raf=requestAnimationFrame(draw)};
    resize();draw();window.addEventListener("resize",resize);return()=>{window.removeEventListener("resize",resize);cancelAnimationFrame(raf)};
  },[]);
  return <canvas ref={ref} className="flow-field" aria-hidden="true"/>;
}

export default function Home(){
  const [lang,setLang]=useState<Lang>("es");
  const [aboutExpanded,setAboutExpanded]=useState(false);
  const [openAboutSection,setOpenAboutSection]=useState<string | null>(null);
  const [activeMetric,setActiveMetric]=useState<number | null>(null);
  useEffect(()=>{const saved=window.localStorage.getItem("mpa-lang");if(saved==="en")setLang("en")},[]);
  const changeLanguage=(next:Lang)=>{setLang(next);window.localStorage.setItem("mpa-lang",next);document.documentElement.lang=next};
  return <main>
    <div className="cosmos" aria-hidden="true"><span className="nebula n1"/><span className="nebula n2"/><span className="stars"/></div>
    <nav className="nav-shell" aria-label={lang==="es"?"Navegación principal":"Main navigation"}><div className="nav-inner">
      <a className="brand" href="#top"><img src="/mpa-flow-logo-final-v7.png" alt="MPA Flow"/><span>Rocío Dopazo</span></a>
      <div className="nav-links"><div className="nav-group"><a href="#profile">{lang==="es"?"Sobre mí":"About"}</a><div className="nav-submenu"><a href="#profile">{lang==="es"?"Perfil profesional":"Professional profile"}</a><a href="#excediendo-caracteres">Excediendo caracteres</a></div></div><a href="#flow">{lang==="es"?"Práctica profesional":"Professional practice"}</a><a href="#work">{lang==="es"?"Trabajo":"Work"}</a><a href="#contact">{lang==="es"?"Contacto":"Contact"}</a></div>
      <div className="language"><button className={lang==="es"?"active":""} onClick={()=>changeLanguage("es")}>ES</button><button className={lang==="en"?"active":""} onClick={()=>changeLanguage("en")}>EN</button></div>
    </div></nav>
    <header id="top" className="hero"><img className="hero-city" src="/mar-del-plata-night.png" alt="" aria-hidden="true"/><div className="container hero-layout">
      <div className="hero-content"><p className="eyebrow">Systems · Transformation · Technology &amp; AI</p><h1>Rocío Dopazo</h1><p className="hero-tagline">Making complexity visible. Designing transformation.</p>
        <p className="hero-role">Systems &amp; Change Architect <span>|</span> IT Delivery Manager <span>|</span> E2E Delivery &amp; Ops <span>|</span> Applied AI</p><p className="hero-location">Mar del Plata, {lang==="es"?"Provincia de Buenos Aires, Argentina":"Buenos Aires Province, Argentina"}</p>
        <p className="availability">{lang==="es"?"Disponible para roles remotos e híbridos en Mar del Plata, y proyectos de transformación a través de MPA Flow.":"Available for remote and hybrid roles in Mar del Plata, and transformation projects through MPA Flow."}</p>
        <div className="hero-actions"><a className="button primary" href="#work">{lang==="es"?"Ver proyectos":"See projects"}</a><a className="button secondary" href="#contact">{lang==="es"?"Contacto":"Contact"}</a></div>
      </div>
      <figure className="hero-portrait"><img src="/rocio-portrait-final-v7.jpeg" alt="Retrato profesional de Rocío Dopazo"/><figcaption>Systems &amp; Change Architect</figcaption></figure>
    </div></header>
    <aside className="metrics-ticker" aria-label={lang==="es"?"Experiencia profesional":"Professional experience"}><div className="ticker-track">{[0,1,2,3].map(copy=><div className="ticker-set" aria-hidden={copy!==0} key={copy}>{[
      {n:"18+",es:"Trayectoria",en:"Track record"},{n:"25+",es:"Iniciativas tech",en:"Tech initiatives"},{n:"30+",es:"Profesionales liderados",en:"Professionals led"},{n:"3",es:"Soluciones AI en producción",en:"AI solutions in production"},{n:"2°",es:"Premio AI Weekend 2026",en:"AI Weekend 2026 award"}
    ].map(item=><span className="ticker-item" key={`${copy}-${item.es}`}><b>{item.n}</b> {lang==="es"?item.es:item.en}<i>·</i></span>)}</div>)}</div></aside>
    <section id="excediendo-caracteres" className="section editorial-section"><div className="container">
      <div className="editorial-heading"><div><p className="section-kicker">{lang==="es"?"Escritora · Reflexión & transformación":"Writer · Reflection & transformation"}</p><h2>Excediendo <em>caracteres</em></h2><p className="editorial-intro">{lang==="es"?"Escribo para hacer visible lo que observo, abrir preguntas y transformar experiencia en pensamiento compartido.":"I write to make visible what I observe, open new questions, and transform experience into shared thought."}</p></div><span>01</span></div>
      <a className="editorial-feature" href="/excediendo-caracteres/open-to-work"><div className="editorial-copy"><p className="editorial-meta">27 AGO 2026 · 6 MIN · {lang==="es"?"TRAYECTORIA & CAMBIO":"CAREER & CHANGE"}</p><h3>{lang==="es"?"Estrenando frame.":"Stepping into a new frame."}</h3><p>{lang==="es"?"Volver a mostrarme disponible después de 18 años de trayectoria no fue una decisión menor. Fue una forma de reconocer mi configuración actual y atreverme a construir otra.":"Making myself available again after an 18-year career was not a minor decision. It became a way of acknowledging my current configuration and daring to build a new one."}</p><span>{lang==="es"?"Leer la nota":"Read the note"} <b>→</b></span></div><div className="editorial-visual editorial-frame-visual"><div className="mpa-frame"><i className="frame-orbit orbit-one"/><i className="frame-orbit orbit-two"/><i className="frame-node node-one"/><i className="frame-node node-two"/><i className="frame-node node-three"/><div className="frame-portrait"><img src="/rocio-portrait-final-v7.jpeg" alt={lang==="es"?"Rocío Dopazo en una nueva configuración profesional":"Rocío Dopazo in a new professional configuration"}/></div><span className="frame-word">OPEN <b>TO</b> POSSIBILITY</span></div><small>{lang==="es"?"Una nueva configuración profesional en movimiento.":"A new professional configuration in motion."}</small></div></a>
    </div></section>
    <section id="profile" className="section profile-section" data-content-version="about-v20"><div className="container narrow">
      <p className="section-kicker">{lang==="es"?"Sobre mí":"About"}</p>
      <h2>{lang==="es"
        ? "Hago visible la complejidad para diseñar y materializar transformación"
        : "I make complexity visible to design and deliver transformation"}
      </h2>
      <div className="gradient-rule"/>
      <p className="lead-copy">{lang==="es"?<>Las organizaciones funcionan a través de relaciones entre <strong>procesos, personas, capacidades, información, decisiones, recursos y tecnología</strong>. Esas relaciones configuran cómo fluye —o deja de fluir— el valor a través del sistema.</>:<>Organizations operate through relationships between <strong>processes, people, capabilities, information, decisions, resources and technology</strong>. Those relationships shape how value flows—or stops flowing—through the system.</>}</p>
      <p>{lang==="es"?<>Mi trabajo está en <strong>hacer visible esa configuración</strong>, entender qué está condicionando el resultado y diseñar cómo reconfigurarla.</>:<>My work is to <strong>make that configuration visible</strong>, understand what is conditioning the outcome, and design how to reconfigure it.</>}</p>
      <p>{lang==="es"?<>A veces eso implica transformar un proceso. Otras, reorganizar capacidades y responsabilidades, desarrollar autonomía en los equipos, rediseñar información y governance, implementar una solución tecnológica o incorporar automatización e IA. Y muchas veces implica varias de esas cosas al mismo tiempo.</>:<>Sometimes that means transforming a process. Other times, reorganizing capabilities and responsibilities, developing team autonomy, redesigning information and governance, implementing a technology solution, or incorporating automation and AI. Often it means several of those things at once.</>}</p>
      <p className="lead-copy">{lang==="es"?"Arquitectura para diseñar. Delivery para materializar.":"Architecture to design. Delivery to make it real."}</p>
      <p>{lang==="es"?<>Mi perfil combina <strong>Systems &amp; Change Architecture</strong> con <strong>IT Delivery &amp; Operations Management</strong>.</>:<>My profile combines <strong>Systems &amp; Change Architecture</strong> with <strong>IT Delivery &amp; Operations Management</strong>.</>}</p>
      <p>{lang==="es"?<>La arquitectura me permite observar el sistema de manera integral, identificar relaciones, fricciones, dependencias y capacidades, y diseñar una configuración capaz de producir un resultado diferente.</>:<>Architecture lets me observe the system as a whole, identify relationships, friction, dependencies and capabilities, and design a configuration capable of producing a different outcome.</>}</p>
      <p>{lang==="es"?<>El delivery lleva ese diseño a operación: priorizar, coordinar, implementar, validar, adoptar, observar e iterar hasta que la solución forme parte del funcionamiento real de la organización.</>:<>Delivery takes that design into operation: prioritizing, coordinating, implementing, validating, driving adoption, observing and iterating until the solution becomes part of how the organization actually runs.</>}</p>
      <p>{lang==="es"?<>Por eso no entiendo arquitectura y ejecución como dos momentos desconectados. Diseño sistemas que puedan operar y lidero transformaciones para que efectivamente operen.</>:<>That is why I don't treat architecture and execution as two disconnected moments. I design systems that can operate, and I lead transformations so that they actually do.</>}</p>
      <button className="about-toggle" type="button" aria-expanded={aboutExpanded} aria-controls="about-more" onClick={()=>setAboutExpanded(value=>!value)}>{aboutExpanded?(lang==="es"?"Leer menos":"Read less"):(lang==="es"?"Leer más sobre mi recorrido":"Read more about my journey")}<span aria-hidden="true">{aboutExpanded?"−":"+"}</span></button>
      {aboutExpanded&&<div id="about-more" className="about-more">
        {[
          {id:"capacity",title:{es:"Transformar también es desarrollar capacidad",en:"Transforming also means building capability"},body:<>
            <p>{lang==="es"?<>Una de las variables que más me interesa diseñar es <strong>cómo se distribuye la capacidad dentro del sistema</strong>.</>:<>One of the variables I most care about designing is <strong>how capability is distributed within the system</strong>.</>}</p>
            <p className="evidence-line">{lang==="es"?<>He liderado equipos de <strong>30+ profesionales</strong>, desarrollado <strong>5 líderes</strong> desde roles técnicos para que sus células pudieran operar con autonomía y diseñado una estructura de <strong>7 células dinámicas</strong>, adaptando capacidades a las necesidades del delivery.</>:<>I have led teams of <strong>30+ professionals</strong>, developed <strong>5 leaders</strong> from technical roles so their cells could operate autonomously, and designed a structure of <strong>7 dynamic cells</strong>, adapting capabilities to delivery needs.</>}</p>
            <p>{lang==="es"?<>El objetivo no es generar dependencia de quien lidera la transformación, sino dejar criterio, conocimiento, autonomía y mecanismos de coordinación que permitan sostenerla y evolucionarla.</>:<>The goal is not to create dependency on whoever leads the transformation, but to leave behind judgment, knowledge, autonomy and coordination mechanisms that let it be sustained and evolved.</>}</p>
          </>},
          {id:"tech",title:{es:"Tecnología e IA como capacidades del sistema",en:"Technology and AI as capabilities of the system"},body:<>
            <p>{lang==="es"?<>No parto de una tecnología predeterminada. Primero necesito entender qué resultado buscamos, cómo funciona hoy el sistema y qué necesita cambiar.</>:<>I don't start from a predetermined technology. First I need to understand what outcome we're after, how the system works today, and what needs to change.</>}</p>
            <p>{lang==="es"?<>Desde ahí puedo diseñar procesos y soluciones digitales, coordinar desarrollo interno y proveedores, automatizar operaciones o incorporar IA tanto en productos y soluciones como en delivery, seguimiento y operación.</>:<>From there I can design processes and digital solutions, coordinate in-house development and vendors, automate operations, or incorporate AI both in products and solutions and in delivery, tracking and operations.</>}</p>
            <p>{lang==="es"?<>Hoy cuento con <strong>3 soluciones de IA/automatización en producción</strong> y continúo explorando cómo agentes y nuevas capacidades tecnológicas pueden integrarse a sistemas reales de trabajo.</>:<>Today I have <strong>3 AI/automation solutions in production</strong> and keep exploring how agents and new technology capabilities can integrate into real working systems.</>}</p>
            <p>{lang==="es"?<>Esta mirada también dio lugar a <strong>SkillPath Flow</strong>, plataforma gamificada con IA que co-creé y lideré conceptual y funcionalmente, reconocida con el <strong>2° Premio en AI Weekend San Rafael 2026</strong>.</>:<>This perspective also gave rise to <strong>SkillPath Flow</strong>, a gamified AI platform I co-created and led conceptually and functionally, recognized with <strong>2nd Prize at AI Weekend San Rafael 2026</strong>.</>}</p>
          </>},
          {id:"trajectory",title:{es:"Una trayectoria atravesada por transformación",en:"A career shaped by transformation"},body:<>
            <p>{lang==="es"?<>En <strong className="number-emphasis">18+ años</strong> de trayectoria profesional, casi una década principalmente en tecnología y transformación digital, trabajé en organizaciones públicas y privadas de gobierno, salud, servicios financieros, asistencia al viajero y servicios tecnológicos.</>:<>Across <strong className="number-emphasis">18+ years</strong> of professional experience, nearly a decade of it focused primarily on technology and digital transformation, I have worked in public and private organizations in government, healthcare, financial services, travel assistance and technology services.</>}</p>
            <p className="evidence-line">{lang==="es"?<>Diseñé <strong>20+ proyectos</strong>, participé en la creación y transformación de <strong>1.000+ procesos y trámites</strong>, lideré <strong>25+ iniciativas tecnológicas</strong>, portfolios de <strong>10+ proyectos/clientes simultáneos</strong>, ecosistemas de <strong>5 proveedores tecnológicos</strong> + desarrollo interno y articulación con <strong>40+ stakeholders</strong>.</>:<>I designed <strong>20+ projects</strong>, took part in creating and transforming <strong>1,000+ processes and procedures</strong>, led <strong>25+ technology initiatives</strong>, portfolios of <strong>10+ simultaneous projects/clients</strong>, ecosystems of <strong>5 technology vendors</strong> plus in-house development, and alignment with <strong>40+ stakeholders</strong>.</>}</p>
            <p>{lang==="es"?<>También trabajé sobre sistemas que necesitaban recuperar flujo: <strong>2 cuentas críticas recuperadas</strong>, un área en riesgo reconfigurada y mejoras de <strong>hasta 50%</strong> en procesos.</>:<>I also worked on systems that needed to recover flow: <strong>2 critical accounts recovered</strong>, an at-risk area reconfigured, and improvements of <strong>up to 50%</strong> in processes.</>}</p>
          </>},
          {id:"mpaflow",title:{es:"MPA Flow",en:"MPA Flow"},body:<>
            <p>{lang==="es"?<>De esta manera de observar, diseñar e intervenir sistemas nace <strong>MPA Flow</strong>, mi práctica de arquitectura de sistemas, soluciones tecnológicas y transformación organizacional.</>:<>From this way of observing, designing and intervening in systems comes <strong>MPA Flow</strong>, my practice of systems architecture, technology solutions and organizational transformation.</>}</p>
            <p>{lang==="es"?<>Es también la formalización de una idea que atraviesa mi trabajo: <strong>una transformación no se sostiene solamente por implementar una solución</strong>. Se sostiene cuando el sistema puede observarla, gobernarla y seguir evolucionándola.</>:<>It is also the formalization of an idea that runs through my work: <strong>a transformation is not sustained simply by implementing a solution</strong>. It is sustained when the system can observe it, govern it and keep evolving it.</>}</p>
          </>},
        ].map(section=><div className="about-subsection" key={section.id}>
          <button className="about-subtoggle" type="button" aria-expanded={openAboutSection===section.id} aria-controls={`about-${section.id}`} onClick={()=>setOpenAboutSection(openAboutSection===section.id?null:section.id)}>
            {t(section.title,lang)}<span aria-hidden="true">{openAboutSection===section.id?"−":"+"}</span>
          </button>
          {openAboutSection===section.id&&<div id={`about-${section.id}`} className="about-subbody">{section.body}</div>}
        </div>)}
      </div>}
      <div className="stats" aria-label={lang==="es"?"Evidencia profesional interactiva":"Interactive professional evidence"}>{profileMetrics.map((item,index)=><button className={`stat${activeMetric===index?" active":""}`} type="button" key={item.label.es} aria-expanded={activeMetric===index} onClick={()=>setActiveMetric(activeMetric===index?null:index)}><strong>{item.n}</strong><span>{t(item.label,lang)}</span><small>{lang==="es"?"Explorar":"Explore"} <b aria-hidden="true">{activeMetric===index?"−":"+"}</b></small></button>)}</div>
      {activeMetric!==null&&<article className="metric-detail" aria-live="polite">
        <div><p className="section-kicker">{lang==="es"?"Evidencia + toolkit":"Evidence + toolkit"}</p><h3>{t(profileMetrics[activeMetric].title,lang)}</h3><p>{t(profileMetrics[activeMetric].detail,lang)}</p></div>
        <ul>{profileMetrics[activeMetric].toolkit[lang].map(tool=><li key={tool}>{tool}</li>)}</ul>
      </article>}
    </div></section>
    <section className="city-banner" aria-label="Mar del Plata — Making complexity visible. Designing transformation."><img src="/mar-del-plata-banner-final-v2.png" alt="Vista nocturna de Mar del Plata con la identidad visual de Rocío Dopazo"/></section>
    <section id="flow" className="section flow-section"><div className="container"><div className="flow-heading"><div><p className="section-kicker">{lang==="es"?"Práctica profesional · MPA Flow":"Professional practice · MPA Flow"}</p><h2 className="flow-title">FLOW</h2><p className="flow-intro">{lang==="es"?"Un marco para leer el sistema completo antes de intervenirlo: detectar fricción, orientar la lectura, recuperar ownership y elegir la intervención que corresponde.":"A framework for reading the whole system before intervening in it: detecting friction, orienting the reading, recovering ownership and choosing the intervention that fits."}</p></div><a className="flow-brand" href="https://mpaflow.com/" target="_blank" rel="noreferrer" aria-label={lang==="es"?"Visitar la página de MPA Flow":"Visit the MPA Flow website"}><span className="orbit orbit-one"/><span className="orbit orbit-two"/><img src="/mpa-flow-logo-final-v7.png" alt="Logo de MPA Flow"/><small>{lang==="es"?"Visitar MPA Flow":"Visit MPA Flow"} <b aria-hidden="true">↗</b></small></a></div><div className="flow-stage"><FlowField/><div className="flow-grid">{flow.map(node=><article className="flow-card" key={node.code}><div className="card-top"><span>{node.code}</span><b>{node.number}</b></div><h3>{t(node.title,lang)}</h3><p>{t(node.body,lang)}</p></article>)}</div></div></div></section>
    <section id="work" className="section work-section"><div className="container"><p className="section-kicker">{lang==="es"?"Trabajo":"Work"}</p><h2>Portfolio</h2><div className="gradient-rule"/>
      {groups.map((group:any)=>{const isMpa=group.title==="MPA Flow";const featured=isMpa?group.projects.filter((project:any)=>project.featured):group.projects;const additional=isMpa?group.projects.filter((project:any)=>!project.featured):[];const cards=(projects:any[])=><div className="projects-grid">{projects.map((project:any)=><article className={`project-card${project.spotlight?" project-card-featured":""}${(project.image||project.images||project.mockup)?" project-card-visual":""}`} key={local(project.title,lang)}>{project.mockup==="narrative-portal"&&<NarrativePortalVisual lang={lang}/>} {project.image&&<figure className="project-visual"><img src={project.image} alt={`${local(project.title,lang)} — ${lang==="es"?"captura del proyecto":"project screenshot"}`}/></figure>}{project.images&&<figure className="project-gallery">{project.images.map((image:string,index:number)=><img src={image} key={image} alt={`${local(project.title,lang)} — ${lang==="es"?"captura":"screenshot"} ${index+1}`}/>)}</figure>}<h4>{local(project.title,lang)}</h4><p className="project-tagline">{t(project.tagline,lang)}</p><p>{t(project.body,lang)}</p>{project.badge&&<span className="project-badge">{t(project.badge,lang)}</span>}{project.url?<a href={project.url} target="_blank" rel="noreferrer">{lang==="es"?"Visitar":"Visit"} <span>→</span></a>:<span className="no-link">{project.status?t(project.status,lang):(lang==="es"?"Prototipo privado":"Private prototype")}</span>}</article>)}</div>;return <div className="project-group" key={local(group.title,lang)}><div className="group-heading"><h3>{local(group.title,lang)}</h3><span>{local(group.label,lang)}</span>{isMpa&&<a className="group-external" href="https://mpaflow.com/" target="_blank" rel="noreferrer">{lang==="es"?"Explorar la práctica completa":"Explore the full practice"} ↗</a>}</div>{cards(featured)}{isMpa&&additional.length>0&&<details className="projects-disclosure"><summary>{lang==="es"?`Ver ${additional.length} desarrollos más`:`View ${additional.length} more developments`}<span aria-hidden="true">+</span></summary>{cards(additional)}</details>}</div>})}
    </div></section>
    <section id="contact" className="section contact-section"><div className="container narrow"><p className="section-kicker">{lang==="es"?"Contacto":"Contact"}</p><h2>{lang==="es"?"Conversemos sobre tu sistema":"Let's talk about your system"}</h2><p className="contact-intro">{lang==="es"?"Escribime si querés revisar la fricción de tus procesos, sistemas o equipos.":"Write to me if you want to look at the friction in your processes, systems or teams."}</p><div className="contact-cards"><a href="mailto:rociocelestedopazo@gmail.com" className="contact-card"><span>Email</span><strong>rociocelestedopazo@gmail.com</strong></a><a href="https://www.linkedin.com/in/rociodopazo" target="_blank" rel="noreferrer" className="contact-card"><span>LinkedIn</span><strong>linkedin.com/in/rociodopazo</strong></a><a href="https://mpaflow.com/" target="_blank" rel="noreferrer" className="contact-card brand-card"><img src="/mpa-flow-logo-final-v7.png" alt="MPA Flow"/><span><small>{lang==="es"?"Práctica profesional":"Professional practice"}</small><strong>MPA Flow</strong></span></a></div></div></section>
    <footer>© 2026 Rocío Dopazo — MPA Flow · Evigila · Lude · Transmuta</footer>
  </main>
}

function MetodoVivoVisual({lang}:{lang:Lang}){
  return <figure className="project-visual metodo-vivo-visual" aria-label={lang==="es"?"Prototipo de Portal de Experiencias":"Experience Portal prototype"}>
    <div className="mv-sidebar">
      <div className="mv-brand"><span>PE</span><strong>{lang==="es"?<>Portal de<br/>Experiencias</>:<>Experience<br/>Portal</>}</strong></div>
      <nav aria-label={lang==="es"?"Módulos del prototipo":"Prototype modules"}>
        {[lang==="es"?"Inicio":"Home",lang==="es"?"Recorrido":"Journey",lang==="es"?"Sesiones":"Sessions",lang==="es"?"Progreso":"Progress",lang==="es"?"Reflexiones":"Reflections",lang==="es"?"Comunidad":"Community"].map((item,index)=><span className={index===0?"active":""} key={item}><i/>{item}</span>)}
      </nav>
      <small>{lang==="es"?"Tu método. Su proceso.":"Your method. Their journey."}</small>
    </div>
    <div className="mv-dashboard">
      <div className="mv-top"><span>{lang==="es"?"Espacio de acompañamiento":"Mentoring space"}</span><b>{lang==="es"?"Progreso 68%":"Progress 68%"}</b></div>
      <div className="mv-hero">
        <img src="/metodo-vivo-mentoring-v12.png" alt="" aria-hidden="true"/>
        <div className="mv-hero-copy"><small>{lang==="es"?"RECORRIDO ACTIVO":"ACTIVE JOURNEY"}</small><strong>{lang==="es"?"Convertí intención en transformación.":"Turn intention into transformation."}</strong><p>{lang==="es"?"Herramientas, sesiones y evidencia de progreso en una experiencia con tu identidad.":"Tools, sessions and visible progress in an experience built around your identity."}</p><span>{lang==="es"?"Continuar recorrido →":"Continue journey →"}</span></div>
      </div>
      <div className="mv-cards"><div><small>{lang==="es"?"PRÓXIMA SESIÓN":"NEXT SESSION"}</small><strong>{lang==="es"?"Claridad para decidir":"Clarity to decide"}</strong><span>{lang==="es"?"Preparar encuentro":"Prepare session"}</span></div><div><small>{lang==="es"?"REFLEXIÓN":"REFLECTION"}</small><strong>{lang==="es"?"¿Qué cambió desde la última conversación?":"What changed since the last conversation?"}</strong><span>{lang==="es"?"Registrar avance":"Capture progress"}</span></div><div><small>{lang==="es"?"HERRAMIENTA":"TOOL"}</small><strong>{lang==="es"?"Mapa de decisiones":"Decision map"}</strong><span>{lang==="es"?"Abrir herramienta":"Open tool"}</span></div></div>
    </div>
  </figure>
}

function NarrativePortalVisual({lang}:{lang:Lang}){
  const steps=lang==="es"?["LIBRO FÍSICO","ACCESO PROTEGIDO","EXPERIENCIA DIGITAL"]:["PHYSICAL BOOK","PROTECTED ACCESS","DIGITAL EXPERIENCE"];
  return <figure className="project-visual narrative-portal-visual" aria-label={lang==="es"?"Del libro físico al portal narrativo interactivo":"From the physical book to the interactive narrative portal"}>
    <div className="np-panel np-book"><img src="/que-embole-book-cover-v14.jpeg" alt={lang==="es"?"Ejemplar físico del libro ¡Qué Embole!":"Physical copy of the book ¡Qué Embole!"}/><span><b>01</b>{steps[0]}</span></div>
    <i className="np-arrow" aria-hidden="true">→</i>
    <div className="np-panel np-access"><img src="/que-embole-portal-access-v14.jpeg" alt={lang==="es"?"Página del libro con acceso al portal de integración":"Book page containing access to an integration portal"}/><div className="qr-protection" aria-label={lang==="es"?"Código protegido":"Protected code"}><strong>MPA</strong><small>{lang==="es"?"ACCESO PROTEGIDO":"PROTECTED ACCESS"}</small></div><span><b>02</b>{steps[1]}</span></div>
    <i className="np-arrow" aria-hidden="true">→</i>
    <div className="np-panel np-portal"><img src="/que-embole-portals-v14.png" alt={lang==="es"?"Portal digital del universo ¡Qué Embole!":"Digital portal for the ¡Qué Embole! universe"}/><span><b>03</b>{steps[2]}</span></div>
  </figure>
}
