"use client";

import { useEffect, useRef, useState } from "react";

type Lang = "es" | "en";
type Copy = { es: string; en: string };
const t = (copy: Copy, lang: Lang) => copy[lang];
const local = (value: string | Copy, lang: Lang) => typeof value === "string" ? value : value[lang];

const flow = [
  { code:"FRICTION", number:"01", title:{es:"Discernir para decidir",en:"Discern to decide"}, body:{es:"Detectar dónde está la fricción real. Distinguir entre ruido y señal. Identificar qué configuraciones generan resistencia.",en:"Detect where the real friction lives. Distinguish noise from signal. Identify which configurations generate resistance."}},
  { code:"LEAD", number:"02", title:{es:"Observar para orientar",en:"Observe to orient"}, body:{es:"Identificar los patrones invisibles que operan en el sistema. Ver lo que frena antes de proponer lo que mueve.",en:"Identify the invisible patterns operating within the system. See what holds it back before proposing what moves it."}},
  { code:"OWNERSHIP", number:"03", title:{es:"Elegir para construir",en:"Choose to build"}, body:{es:"Recuperar agencia sobre el sistema. Definir sobre qué se puede actuar realmente y desde ahí construir.",en:"Recover agency over the system. Define what can actually be acted upon, and build from there."}},
  { code:"WISDOM", number:"04", title:{es:"Comprender para responder",en:"Understand to respond"}, body:{es:"Integrar la información del sistema. Reconocer qué intervención corresponde. No toda fricción requiere la misma respuesta.",en:"Integrate the system's information. Recognize which intervention fits. Not every friction calls for the same response."}},
];

const profileMetrics = [
  {n:"18+",label:{es:"Años de experiencia",en:"Years of experience"},title:{es:"Trayectoria transversal",en:"Cross-functional experience"},detail:{es:"Transformación organizacional, gestión pública, diseño institucional, proyectos y casi una década desarrollada principalmente en tecnología.",en:"Organizational transformation, public management, institutional design, projects, and nearly a decade focused primarily on technology."},toolkit:{es:["Systems thinking","Diseño organizacional","Transformación digital","Mejora continua"],en:["Systems thinking","Organizational design","Digital transformation","Continuous improvement"]}},
  {n:"40+",label:{es:"Stakeholders",en:"Stakeholders"},title:{es:"Gobernanza de ecosistemas",en:"Ecosystem governance"},detail:{es:"Articulación entre negocio, tecnología y liderazgo dentro de ecosistemas que incluyeron hasta 5 vendors.",en:"Alignment across business, technology and leadership within ecosystems involving up to 5 vendors."},toolkit:{es:["Stakeholder mapping","Gobernanza","Cadencias ejecutivas","Gestión de vendors"],en:["Stakeholder mapping","Governance","Executive cadences","Vendor management"]}},
  {n:"30+",label:{es:"Personas lideradas",en:"People led"},title:{es:"Talento y capacidad instalada",en:"Talent & lasting capability"},detail:{es:"Liderazgo de equipos, adopción del cambio y transferencia de conocimiento para construir autonomía sostenible.",en:"Team leadership, change adoption and knowledge transfer to build sustainable autonomy."},toolkit:{es:["Change Management","Capability building","Knowledge transfer","Team leadership"],en:["Change Management","Capability building","Knowledge transfer","Team leadership"]}},
  {n:"25+",label:{es:"Iniciativas",en:"Initiatives"},title:{es:"Delivery y portfolios complejos",en:"Complex delivery & portfolios"},detail:{es:"Gestión simultánea de iniciativas y portfolios de 10+ proyectos, conectando prioridades, riesgos, dependencias y capacidad.",en:"Concurrent initiative management and portfolios of 10+ projects, connecting priorities, risks, dependencies and capacity."},toolkit:{es:["IT Delivery","Portfolio governance","Priorización","Riesgos y dependencias"],en:["IT Delivery","Portfolio governance","Prioritization","Risks & dependencies"]}},
  {n:"3",label:{es:"Soluciones de IA end-to-end",en:"End-to-end AI solutions"},title:{es:"IA aplicada al sistema",en:"AI applied to the system"},detail:{es:"Soluciones diseñadas desde la necesidad y el proceso hasta la experiencia, adopción y evolución operativa.",en:"Solutions designed from need and process through experience, adoption and operational evolution."},toolkit:{es:["IA aplicada","Análisis funcional","Diseño de producto","Prototipado end-to-end"],en:["Applied AI","Functional analysis","Product design","End-to-end prototyping"]}},
];

const groups: any[] = [
  { title:"MPA Flow", label:{es:"Productos propios · Proyectos en curso",en:"Original products · Work in progress"}, projects:[
    {title:"SkillPath Flow",featured:true,spotlight:true,tagline:{es:"Talento evaluado por comportamiento real",en:"Talent assessed through real behavior"},body:{es:"Plataforma AI-powered de descubrimiento de talento. Perfiles basados en decisiones reales, no declaraciones. Sistema de niveles, XP y readiness.",en:"AI-powered talent discovery platform. Profiles based on real decisions, not declarations. Levels, XP and readiness system."},badge:{es:"2do lugar — Hackathon IA UTN, abril 2026",en:"2nd place — UTN AI Hackathon, April 2026"},image:"/skillpath-flow-journey-v11.png",url:"https://skillpathflow.com"},
    {title:{es:"Portal de Experiencias",en:"Experience Portal"},featured:true,tagline:{es:"Metodologías, contenidos y comunidad convertidos en una experiencia interactiva",en:"Methods, content and community turned into an interactive experience"},body:{es:"Sistema custom y adaptable para programas de formación, coaching, consultoría, membresías y comunidades. Integra contenidos, sesiones, herramientas, progreso, reflexiones, recursos y acompañamiento dentro de un recorrido digital con identidad propia.",en:"A custom, adaptable system for training, coaching, consulting, membership programs and communities. It brings content, sessions, tools, progress, reflections, resources and support into one branded digital journey."},badge:{es:"Arquitectura de Sistemas Custom · Prototipo",en:"Custom Systems Architecture · Prototype"},image:"/portal-experiencias-anonimo-v16.png",status:{es:"Vista anonimizada",en:"Anonymized preview"}},
    {title:{es:"Sistema de onboarding operativo",en:"Operational onboarding system"},tagline:{es:"Procesos, entrenamiento y autonomía para equipos comerciales",en:"Processes, enablement and autonomy for sales teams"},body:{es:"Dispositivo de onboarding que centraliza el flujo completo de captación, precomercialización y venta, junto con procesos documentados, preguntas frecuentes y tareas por rol. Permite que cada productor comprenda cómo operar y avance con autonomía, sin depender permanentemente del dueño o director de la inmobiliaria.",en:"An onboarding system that centralizes the full acquisition, pre-market and sales flow, together with documented processes, FAQs and role-based tasks. It enables each producer to understand how to operate and move forward autonomously, without constantly depending on the real-estate owner or director."},image:"/proceso-operativo-v16.png",status:{es:"Vista del proceso",en:"Process preview"}},
    {title:{es:"Dashboard de transformación operativa",en:"Operational transformation dashboard"},featured:true,tagline:{es:"Estrategia, brechas, métricas y evolución en una sola arquitectura",en:"Strategy, gaps, metrics and evolution in one architecture"},body:{es:"Tablero para convertir un diagnóstico operativo en un sistema de transformación trazable: estado del proyecto, tres horizontes de evolución, brechas críticas, proceso de venta, KPIs y cronograma.",en:"A dashboard that turns an operational diagnosis into a traceable transformation system: project status, three evolution horizons, critical gaps, sales process, KPIs and roadmap."},image:"/dashboard-transformacion-v16.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
    {title:"ScrumFlix MPA",tagline:{es:"Entrenamiento PSM I gamificado",en:"Gamified PSM I training"},body:{es:"Plataforma jugable de entrenamiento para certificación Scrum. Integra modos de dificultad, niveles progresivos, feedback contextual, diagnóstico de readiness, retrospectiva y microplan de refuerzo adaptativo.",en:"A game-based Scrum certification training platform. It integrates difficulty modes, progressive levels, contextual feedback, readiness diagnostics, retrospectives and an adaptive reinforcement micro-plan."},images:["/scrumflix-question-feedback.png","/scrumflix-retrospective.png"],status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"PSM I Trainer",tagline:{es:"Entrenamiento profundo para PSM I",en:"Deep training for PSM I"},body:{es:"5 niveles progresivos, dailys vivenciales, retros y refuerzo inteligente por concepto. La identidad azul pertenece a este entrenador, no a ScrumFlix.",en:"Five progressive levels, experiential dailies, retros and smart concept-based reinforcement. The blue identity belongs to this trainer, not ScrumFlix."},image:"/psm-trainer-daily-v16.png",status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"Trader Quest",tagline:{es:"Entrenamiento de trading gamificado",en:"Gamified trading training"},body:{es:"Dojo personal para desarrollar criterio real como trader. Combina microaprendizaje visual, desafíos progresivos, feedback experto, XP, rachas y progreso guardado automáticamente.",en:"A personal dojo for developing real trading judgment. It combines visual microlearning, progressive challenges, expert feedback, XP, streaks and automatically saved progress."},images:["/trader-quest-feedback.png","/trader-quest-candlestick.png"],status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:{es:"Radar de Agencia",en:"Agency Radar"},featured:true,tagline:{es:"Hacer visible dónde se concentra —y dónde se fuga— la capacidad de actuar",en:"Making visible where the capacity to act gathers—and where it leaks"},body:{es:"Experiencia interactiva para reconocer fugas de atención, leer la configuración actual y distinguir qué puede avanzar, qué necesita condiciones y qué requiere intervención. Convierte situaciones cotidianas en un mapa visual de presencia y agencia para ensayar decisiones más conscientes.",en:"An interactive experience for recognizing attention leaks, reading the current configuration and distinguishing what can move forward, what needs enabling conditions and what requires intervention. It turns everyday situations into a visual map of presence and agency for testing more conscious decisions."},images:["/egosumrc-attention.png","/egosumrc-configuration.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
    {title:"Código Soma: Alimentorum",featured:true,tagline:{es:"Registro, observación y experimentación convertidos en un sistema personal",en:"Tracking, observation and experimentation turned into a personal system"},body:{es:"Plataforma de autoobservación para registrar experiencias de alimentación, construir una bitácora y explorar correspondencias a lo largo del tiempo. Integra registro guiado, calendario, laboratorio, hipótesis de configuración y exportación para transformar datos cotidianos en aprendizaje personal, sin convertirlos en diagnósticos ni metas rígidas.",en:"A self-observation platform for recording food-related experiences, building a log and exploring correspondences over time. It integrates guided tracking, calendar, laboratory, configuration hypotheses and export tools to turn everyday data into personal learning—without turning it into diagnosis or rigid goals."},images:["/alimentorum-guided-log-clean.png","/alimentorum-lab-clean.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
    {title:"Código Leo",featured:true,tagline:{es:"Diseño y arquitectura de esencia de marca",en:"Brand Essence Design & Architecture"},body:{es:"App de lectura generativa estratégica para descubrir y diseñar la huella distintiva de una marca emprendedora: aquello singular que orienta su identidad, posicionamiento, narrativa y decisiones. Código Leo toma el signo de Leo como código simbólico de identidad, expresión y presencia propia. Va más allá del branding visual y traduce esa esencia en una configuración coherente del proyecto mediante un recorrido de triangulación, indagación y reconfiguración.",en:"A strategic generative-reading app for discovering and designing the distinctive imprint of an entrepreneurial brand: the singular core that guides its identity, positioning, narrative and decisions. Código Leo draws on the Leo sign as a symbolic code for identity, expression and distinctive presence. It goes beyond visual branding, translating that essence into a coherent project configuration through triangulation, inquiry and reconfiguration."},images:["/codigo-leo-entry.png","/codigo-leo-flow.png"],status:{es:"Desarrollo propio · Experiencia protegida",en:"Original development · Protected experience"}},
  ]},
  { title:{es:"Productos y experiencias digitales",en:"Digital products & experiences"}, label:{es:"Arquitectura de producto · Casos anonimizados",en:"Product architecture · Anonymized cases"}, projects:[
    {title:"Growth Clarity Finder",tagline:{es:"Una experiencia digital que amplía y posiciona la propuesta de valor de un libro",en:"A digital experience that extends and positions a book's value proposition"},body:{es:"Producto digital diseñado para que un libro deje de ser una pieza estática y se convierta en la puerta de entrada a una experiencia interactiva. Traduce sus ideas en un recorrido de diagnóstico, reflexión y acción que ayuda a posicionar la obra, profundizar su propuesta de valor y extender el vínculo con sus lectores.",en:"A digital product designed to turn a book from a static asset into the entry point to an interactive experience. It translates the book's ideas into a journey of diagnosis, reflection and action that helps position the work, deepen its value proposition and extend the relationship with its readers."},image:"/growth-clarity-anonimo-v16.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
    {title:{es:"Atlas Sistémico Organizacional",en:"Organizational System Atlas"},tagline:{es:"Hacer visible qué existe, qué falta y qué sostiene cada parte del sistema",en:"Making visible what exists, what is missing and what supports each part of the system"},body:{es:"Producto digital para mapear personas, recursos, reuniones, preguntas, iniciativas y dependencias. Convierte información dispersa en una arquitectura operativa navegable y exportable.",en:"A digital product for mapping people, resources, meetings, questions, initiatives and dependencies. It turns scattered information into a navigable and exportable operating architecture."},image:"/system-atlas-anonymized.png",status:{es:"Caso anonimizado",en:"Anonymized case"}},
  ]},
  { title:{es:"Experiencias narrativas",en:"Narrative experiences"}, label:"MPA Universe · Stray Sheep", projects:[
    {title:{es:"Portales de Integración — Universo ¡Qué Embole!",en:"Integration Portals — ¡Qué Embole! Universe"},tagline:{es:"La lectura no termina en la página: continúa como experiencia",en:"The reading does not end on the page: it continues as an experience"},body:{es:"Sistema narrativo interactivo que conecta el libro físico con tres recorridos digitales desbloqueables. Códigos de acceso, contenido condicionado, personajes, pruebas y distintas etapas de integración convierten la obra en una experiencia transmedia.",en:"An interactive narrative system connecting the physical book with three unlockable digital journeys. Access codes, conditional content, characters, challenges and progressive integration stages turn the work into a transmedia experience."},mockup:"narrative-portal",status:{es:"Acceso protegido · Se muestran solo capturas",en:"Protected access · Screenshots only"}},
    {title:"De las Patrañas",tagline:{es:"Tres puertas. Tres formas de mirar la bola.",en:"Three doors. Three ways to look at the ball."},body:{es:"Portal de integración de la segunda parte del libro. Detectá las patrañas del sistema.",en:"Integration portal for the second part of the book. Spot the system's patrañas."},status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:"Nigredo Ludus",tagline:{es:"El detector de Nigredo — ¿en qué etapa del proceso estás?",en:"The Nigredo detector — what stage of the process are you in?"},body:{es:"Herramienta simbólica de detección.",en:"Symbolic detection tool."},status:{es:"Experiencia protegida",en:"Protected experience"}},
    {title:{es:"Reto de Iniciación",en:"Initiation Challenge"},tagline:{es:"Tres señales. Una llave. Un umbral.",en:"Three signs. One key. One threshold."},body:{es:"Experiencia de acceso condicional al universo MPA.",en:"A conditional-access experience into the MPA universe."},status:{es:"Experiencia protegida",en:"Protected experience"}},
  ]},
  { title:{es:"Herramientas propias",en:"Own tools"}, label:"MPA Tools", projects:[
    {title:"DIMA — Conjuratio Dominus",tagline:{es:"No busques una definición. Buscá una revelación.",en:"Don't look for a definition. Look for a revelation."},body:{es:"Decodificación simbólica, tres modos de análisis y modelo freemium.",en:"Symbolic decoding, three analysis modes and a freemium model."},url:"https://dima-pi.vercel.app"},
  ]},
];

function FlowField(){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=ref.current;if(!canvas)return;
    const ctx=canvas.getContext("2d");if(!ctx)return;
    const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const particles=Array.from({length:72},()=>({p:Math.random(),speed:.0007+Math.random()*.0015,segment:Math.floor(Math.random()*4),size:.7+Math.random()*1.8,gold:Math.random()<.18}));
    let frame=0,raf=0,w=0,h=0;
    const resize=()=>{const box=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);w=box.width;h=box.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};
    const point=(a:{x:number;y:number},b:{x:number;y:number},p:number,cx:number,cy:number)=>{const c1={x:cx+(a.x-cx)*.2,y:cy+(a.y-cy)*.2};const c2={x:cx+(b.x-cx)*.2,y:cy+(b.y-cy)*.2};const q0={x:a.x+(c1.x-a.x)*p,y:a.y+(c1.y-a.y)*p};const q1={x:c1.x+(cx-c1.x)*p,y:c1.y+(cy-c1.y)*p};const q2={x:cx+(c2.x-cx)*p,y:cy+(c2.y-cy)*p};const r0={x:q0.x+(q1.x-q0.x)*p,y:q0.y+(q1.y-q0.y)*p};const r1={x:q1.x+(q2.x-q1.x)*p,y:q1.y+(q2.y-q1.y)*p};return{x:r0.x+(r1.x-r0.x)*p,y:r0.y+(r1.y-r0.y)*p}};
    const draw=()=>{ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,rx=Math.min(w*.42,520),ry=Math.min(h*.42,360);const nodes=[{x:cx,y:cy-ry},{x:cx+rx,y:cy},{x:cx,y:cy+ry},{x:cx-rx,y:cy}];
      for(let i=0;i<4;i++){const a=nodes[i],b=nodes[(i+1)%4];const c1x=cx+(a.x-cx)*.2,c1y=cy+(a.y-cy)*.2,c2x=cx+(b.x-cx)*.2,c2y=cy+(b.y-cy)*.2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo(c1x,c1y,c2x,c2y,b.x,b.y);ctx.strokeStyle="rgba(196,90,211,.18)";ctx.lineWidth=12;ctx.stroke();ctx.strokeStyle="rgba(208,96,217,.42)";ctx.lineWidth=2;ctx.stroke()}
      particles.forEach(p=>{if(!reduced){p.p+=p.speed;if(p.p>1){p.p=0;p.segment=(p.segment+1)%4}}const pos=point(nodes[p.segment],nodes[(p.segment+1)%4],p.p,cx,cy);ctx.beginPath();ctx.arc(pos.x,pos.y,p.size,0,Math.PI*2);ctx.fillStyle=p.gold?"rgba(201,163,110,.8)":"rgba(234,164,240,.72)";ctx.fill()});
      const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.min(w,h)*.25);glow.addColorStop(0,"rgba(208,96,217,.24)");glow.addColorStop(1,"rgba(156,77,255,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,Math.min(w,h)*.25,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(cx,cy);ctx.rotate(frame*.002);ctx.setLineDash([18,12]);ctx.strokeStyle="rgba(201,163,110,.28)";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,Math.min(w,h)*.12,0,Math.PI*2);ctx.stroke();ctx.restore();frame++;if(!reduced)raf=requestAnimationFrame(draw)};
    resize();draw();window.addEventListener("resize",resize);return()=>{window.removeEventListener("resize",resize);cancelAnimationFrame(raf)};
  },[]);
  return <canvas ref={ref} className="flow-field" aria-hidden="true"/>;
}

export default function Home(){
  const [lang,setLang]=useState<Lang>("es");
  const [aboutExpanded,setAboutExpanded]=useState(false);
  const [activeMetric,setActiveMetric]=useState<number | null>(null);
  useEffect(()=>{const saved=window.localStorage.getItem("mpa-lang");if(saved==="en")setLang("en")},[]);
  const changeLanguage=(next:Lang)=>{setLang(next);window.localStorage.setItem("mpa-lang",next);document.documentElement.lang=next};
  return <main>
    <div className="cosmos" aria-hidden="true"><span className="nebula n1"/><span className="nebula n2"/><span className="stars"/></div>
    <nav className="nav-shell" aria-label={lang==="es"?"Navegación principal":"Main navigation"}><div className="nav-inner">
      <a className="brand" href="#top"><img src="/mpa-flow-logo-final-v7.png" alt="MPA Flow"/><span>Rocío Dopazo</span></a>
      <div className="nav-links"><a href="#profile">{lang==="es"?"Sobre mí":"About"}</a><a href="#flow">{lang==="es"?"Práctica profesional":"Professional practice"}</a><a href="#work">{lang==="es"?"Trabajo":"Work"}</a><a href="#contact">{lang==="es"?"Contacto":"Contact"}</a></div>
      <div className="language"><button className={lang==="es"?"active":""} onClick={()=>changeLanguage("es")}>ES</button><button className={lang==="en"?"active":""} onClick={()=>changeLanguage("en")}>EN</button></div>
    </div></nav>
    <header id="top" className="hero"><img className="hero-city" src="/mar-del-plata-night.png" alt="" aria-hidden="true"/><div className="container hero-layout">
      <div className="hero-content"><p className="eyebrow">Systems · Transformation · Technology &amp; AI</p><h1>Rocío Dopazo</h1><p className="hero-tagline">Making complexity visible. Designing transformation.</p>
        <p className="hero-role">Systems &amp; Change Architect <span>|</span> IT Delivery Manager <span>|</span> Digital Transformation</p><p className="hero-location">Mar del Plata, {lang==="es"?"Provincia de Buenos Aires, Argentina":"Buenos Aires Province, Argentina"}</p>
        <p className="availability">{lang==="es"?"Disponible para roles remotos, oportunidades híbridas en Mar del Plata y proyectos de consultoría.":"Available for remote roles, hybrid opportunities in Mar del Plata and consulting projects."}</p>
        <div className="hero-actions"><a className="button primary" href="#work">{lang==="es"?"Ver proyectos":"See projects"}</a><a className="button secondary" href="#contact">{lang==="es"?"Contacto":"Contact"}</a></div>
      </div>
      <figure className="hero-portrait"><img src="/rocio-portrait-final-v7.jpeg" alt="Retrato profesional de Rocío Dopazo"/><figcaption>Systems &amp; Change Architect</figcaption></figure>
    </div></header>
    <aside className="metrics-ticker" aria-label={lang==="es"?"Experiencia profesional":"Professional experience"}><div className="ticker-track">{[0,1].map(copy=><div className="ticker-set" aria-hidden={copy===1} key={copy}>{[
      {n:"18",es:"Años de experiencia",en:"Years of experience"},{n:"40+",es:"Stakeholders",en:"Stakeholders"},{n:"30+",es:"Personas lideradas",en:"People led"},{n:"25+",es:"Iniciativas",en:"Initiatives"},{n:"3",es:"Soluciones de IA end-to-end",en:"End-to-end AI solutions"}
    ].map(item=><span className="ticker-item" key={`${copy}-${item.es}`}><b>{item.n}</b> {lang==="es"?item.es:item.en}<i>·</i></span>)}</div>)}</div></aside>
    <section id="profile" className="section profile-section" data-content-version="about-v20"><div className="container narrow">
      <p className="section-kicker">{lang==="es"?"Sobre mí":"About"}</p>
      <h2>{lang==="es"
        ? "Arquitectura de sistemas, Delivery Management y gestión del cambio organizacional"
        : "Systems Architecture, Delivery Management & Organizational Change"}
      </h2>
      <div className="gradient-rule"/>
      <p className="lead-copy">{lang==="es"?<>Diseño y lidero la <strong>transformación de sistemas complejos</strong> conectando personas, procesos, información, decisiones y tecnología.</>:<>I design and lead the <strong>transformation of complex systems</strong> by connecting people, processes, information, decisions and technology.</>}</p>
      <p>{lang==="es"?<>Mi trabajo comienza donde una organización encuentra fricción: procesos que no escalan, información dispersa, decisiones desconectadas, capacidades que necesitan reorganizarse o tecnologías que todavía no funcionan como parte de un verdadero sistema.</>:<>My work begins where an organization encounters friction: processes that do not scale, scattered information, disconnected decisions, capabilities that need to be reorganized, or technologies that do not yet operate as part of a true system.</>}</p>
      <p>{lang==="es"?<>Cuento con <strong className="number-emphasis">+18 años</strong> de trayectoria en transformación organizacional, gestión, diseño de proyectos y mejora de procesos, con <strong>casi una década principalmente en tecnología</strong>. He liderado transformación digital, <strong>IT Delivery</strong> end-to-end, reingeniería de procesos, análisis funcional y <strong>Change Management especialmente tecnológico</strong>, articulando negocio, equipos técnicos, proveedores y stakeholders.</>:<>I bring <strong className="number-emphasis">18+ years</strong> of experience in organizational transformation, management, project design and process improvement, with <strong>nearly a decade focused primarily on technology</strong>. I have led digital transformation, end-to-end <strong>IT Delivery</strong>, process reengineering, functional analysis and <strong>Change Management—particularly technology-enabled change</strong>—across business areas, technical teams, vendors and stakeholders.</>}</p>
      <button className="about-toggle" type="button" aria-expanded={aboutExpanded} aria-controls="about-more" onClick={()=>setAboutExpanded(value=>!value)}>{aboutExpanded?(lang==="es"?"Leer menos":"Read less"):(lang==="es"?"Leer más sobre mi recorrido":"Read more about my journey")}<span aria-hidden="true">{aboutExpanded?"−":"+"}</span></button>
      {aboutExpanded&&<div id="about-more" className="about-more">
        <p>{lang==="es"?<>Mi diferencial no está en aplicar una herramienta a un problema, sino en <strong>comprender el sistema y configurar las capacidades necesarias para transformarlo</strong>. Según el contexto, puedo diseñar una nueva arquitectura, liderar el delivery de una existente, reconfigurar procesos y equipos o facilitar la adopción de nuevas tecnologías y formas de trabajo.</>:<>My distinctive value is not applying a tool to a problem, but <strong>understanding the system and configuring the capabilities needed to transform it</strong>. Depending on the context, I can design a new architecture, lead the delivery of an existing one, reconfigure processes and teams, or enable the adoption of new technologies and ways of working.</>}</p>
        <p>{lang==="es"?<>Mi recorrido comenzó en gestión pública, investigación aplicada, diseño institucional y modelos de gestión. Esa base evolucionó hacia la transformación digital, incorporando <strong>Systems Architecture, reingeniería de procesos, análisis funcional, gobernanza</strong>, metodologías ágiles, gestión de productos y proyectos, experiencia de usuario e inteligencia artificial aplicada.</>:<>My career began in public management, applied research, institutional design and management models. That foundation evolved into digital transformation, incorporating <strong>Systems Architecture, process reengineering, functional analysis, governance</strong>, agile methods, product and project management, user experience and applied artificial intelligence.</>}</p>
        <p className="evidence-line">{lang==="es"?<>He liderado <strong>25+ iniciativas</strong> simultáneas, ecosistemas de <strong>5 vendors</strong> y <strong>40+ stakeholders</strong>, además de portfolios de <strong>10+ proyectos</strong> y equipos de <strong>30+ personas</strong>, trabajando sobre prioridades, riesgos, capacidad y evolución de soluciones.</>:<>I have led <strong>25+ concurrent initiatives</strong>, ecosystems involving <strong>5 vendors</strong> and <strong>40+ stakeholders</strong>, as well as portfolios of <strong>10+ projects</strong> and teams of <strong>30+ people</strong>, working across priorities, risks, capacity and solution evolution.</>}</p>
        <p>{lang==="es"?<>Mi enfoque integra <strong>arquitectura, delivery y gestión del cambio</strong>. Una solución no transforma por existir: necesita integrarse con procesos, talento y formas de decisión, ser adoptada y transferir conocimiento para desarrollar capacidades, dejar capacidad instalada y permitir que la organización la sostenga y evolucione con autonomía.</>:<>My approach integrates <strong>architecture, delivery and change management</strong>. A solution does not create transformation simply by existing: it must integrate with processes, talent and decision-making, be adopted, and transfer knowledge to build capabilities, leave lasting capacity, and enable the organization to sustain and evolve it autonomously.</>}</p>
        <p>{lang==="es"?<>Actualmente desarrollo mi práctica profesional en <strong>arquitectura de sistemas, transformación tecnológica y diseño del cambio</strong>, aplicando esta mirada a distintos contextos, roles y configuraciones organizacionales.</>:<>I currently develop my professional practice across <strong>systems architecture, technology transformation and change design</strong>, applying this perspective to different contexts, roles and organizational configurations.</>}</p>
        <p>{lang==="es"?<>A través de <strong>MPA Flow</strong>, esta perspectiva también toma forma como una práctica de arquitectura de sistemas y transformación organizacional, conectando procesos, talento, tecnología e IA aplicada para diseñar nuevas formas de operar y desarrollar capacidades sostenibles.</>:<>Through <strong>MPA Flow</strong>, this perspective also takes shape as a systems architecture and organizational transformation practice, connecting processes, talent, technology and applied AI to design new ways of operating and build sustainable capabilities.</>}</p>
      </div>}
      <div className="stats" aria-label={lang==="es"?"Evidencia profesional interactiva":"Interactive professional evidence"}>{profileMetrics.map((item,index)=><button className={`stat${activeMetric===index?" active":""}`} type="button" key={item.label.es} aria-expanded={activeMetric===index} onClick={()=>setActiveMetric(activeMetric===index?null:index)}><strong>{item.n}</strong><span>{t(item.label,lang)}</span><small>{lang==="es"?"Explorar":"Explore"} <b aria-hidden="true">{activeMetric===index?"−":"+"}</b></small></button>)}</div>
      {activeMetric!==null&&<article className="metric-detail" aria-live="polite">
        <div><p className="section-kicker">{lang==="es"?"Evidencia + toolkit":"Evidence + toolkit"}</p><h3>{t(profileMetrics[activeMetric].title,lang)}</h3><p>{t(profileMetrics[activeMetric].detail,lang)}</p></div>
        <ul>{profileMetrics[activeMetric].toolkit[lang].map(tool=><li key={tool}>{tool}</li>)}</ul>
      </article>}
    </div></section>
    <section className="city-banner" aria-label="Mar del Plata — Making complexity visible. Designing transformation."><img src="/mar-del-plata-banner-final-v2.png" alt="Vista nocturna de Mar del Plata con la identidad visual de Rocío Dopazo"/></section>
    <section id="flow" className="section flow-section"><div className="container"><div className="flow-heading"><div><p className="section-kicker">{lang==="es"?"Práctica profesional · MPA Flow":"Professional practice · MPA Flow"}</p><h2 className="flow-title">FLOW</h2><p className="flow-intro">{lang==="es"?"Un marco para leer el sistema completo antes de intervenirlo: detectar fricción, orientar la lectura, recuperar ownership y elegir la intervención que corresponde.":"A framework for reading the whole system before intervening in it: detecting friction, orienting the reading, recovering ownership and choosing the intervention that fits."}</p></div><a className="flow-brand" href="https://mpaflowpage.netlify.app" target="_blank" rel="noreferrer" aria-label={lang==="es"?"Visitar la página de MPA Flow":"Visit the MPA Flow website"}><span className="orbit orbit-one"/><span className="orbit orbit-two"/><img src="/mpa-flow-logo-final-v7.png" alt="Logo de MPA Flow"/><small>{lang==="es"?"Visitar MPA Flow":"Visit MPA Flow"} <b aria-hidden="true">↗</b></small></a></div><div className="flow-stage"><FlowField/><div className="flow-grid">{flow.map(node=><article className="flow-card" key={node.code}><div className="card-top"><span>{node.code}</span><b>{node.number}</b></div><h3>{t(node.title,lang)}</h3><p>{t(node.body,lang)}</p></article>)}</div></div></div></section>
    <section id="work" className="section work-section"><div className="container"><p className="section-kicker">{lang==="es"?"Trabajo":"Work"}</p><h2>Portfolio</h2><div className="gradient-rule"/>
      {groups.map((group:any)=>{const isMpa=group.title==="MPA Flow";const featured=isMpa?group.projects.filter((project:any)=>project.featured):group.projects;const additional=isMpa?group.projects.filter((project:any)=>!project.featured):[];const cards=(projects:any[])=><div className="projects-grid">{projects.map((project:any)=><article className={`project-card${project.spotlight?" project-card-featured":""}${(project.image||project.images||project.mockup)?" project-card-visual":""}`} key={local(project.title,lang)}>{project.mockup==="narrative-portal"&&<NarrativePortalVisual lang={lang}/>} {project.image&&<figure className="project-visual"><img src={project.image} alt={`${local(project.title,lang)} — ${lang==="es"?"captura del proyecto":"project screenshot"}`}/></figure>}{project.images&&<figure className="project-gallery">{project.images.map((image:string,index:number)=><img src={image} key={image} alt={`${local(project.title,lang)} — ${lang==="es"?"captura":"screenshot"} ${index+1}`}/>)}</figure>}<h4>{local(project.title,lang)}</h4><p className="project-tagline">{t(project.tagline,lang)}</p><p>{t(project.body,lang)}</p>{project.badge&&<span className="project-badge">{t(project.badge,lang)}</span>}{project.url?<a href={project.url} target="_blank" rel="noreferrer">{lang==="es"?"Visitar":"Visit"} <span>→</span></a>:<span className="no-link">{project.status?t(project.status,lang):(lang==="es"?"Prototipo privado":"Private prototype")}</span>}</article>)}</div>;return <div className="project-group" key={local(group.title,lang)}><div className="group-heading"><h3>{local(group.title,lang)}</h3><span>{local(group.label,lang)}</span>{isMpa&&<a className="group-external" href="https://mpaflowpage.netlify.app" target="_blank" rel="noreferrer">{lang==="es"?"Explorar la práctica completa":"Explore the full practice"} ↗</a>}</div>{cards(featured)}{isMpa&&additional.length>0&&<details className="projects-disclosure"><summary>{lang==="es"?`Ver ${additional.length} desarrollos más`:`View ${additional.length} more developments`}<span aria-hidden="true">+</span></summary>{cards(additional)}</details>}</div>})}
    </div></section>
    <section id="contact" className="section contact-section"><div className="container narrow"><p className="section-kicker">{lang==="es"?"Contacto":"Contact"}</p><h2>{lang==="es"?"Conversemos sobre tu sistema":"Let's talk about your system"}</h2><p className="contact-intro">{lang==="es"?"Escribime si querés revisar la fricción de tus procesos, sistemas o equipos.":"Write to me if you want to look at the friction in your processes, systems or teams."}</p><div className="contact-cards"><a href="mailto:rociocelestedopazo@gmail.com" className="contact-card"><span>Email</span><strong>rociocelestedopazo@gmail.com</strong></a><a href="https://www.linkedin.com/in/rociodopazo" target="_blank" rel="noreferrer" className="contact-card"><span>LinkedIn</span><strong>linkedin.com/in/rociodopazo</strong></a><a href="https://mpaflowpage.netlify.app" target="_blank" rel="noreferrer" className="contact-card brand-card"><img src="/mpa-flow-logo-final-v7.png" alt="MPA Flow"/><span><small>{lang==="es"?"Práctica profesional":"Professional practice"}</small><strong>MPA Flow</strong></span></a></div></div></section>
    <footer>© 2026 Rocío Dopazo — MPA Flow · Evigila · Lude · Transmuta</footer>
  </main>
}

function MetodoVivoVisual({lang}:{lang:Lang}){
  return <figure className="project-visual metodo-vivo-visual" aria-label={lang==="es"?"Prototipo de Portal de Experiencias":"Experience Portal prototype"}>
    <div className="mv-sidebar">
      <div className="mv-brand"><span>PE</span><strong>{lang==="es"?<>Portal de<br/>Experiencias</>:<>Experience<br/>Portal</>}</strong></div>
      <nav aria-label={lang==="es"?"Módulos del prototipo":"Prototype modules"}>
        {[lang==="es"?"Inicio":"Home",lang==="es"?"Recorrido":"Journey",lang==="es"?"Sesiones":"Sessions",lang==="es"?"Progreso":"Progress",lang==="es"?"Reflexiones":"Reflections",lang==="es"?"Comunidad":"Community"].map((item,index)=><span className={index===0?"active":""} key={item}><i/>{item}</span>)}
      </nav>
      <small>{lang==="es"?"Tu método. Su proceso.":"Your method. Their journey."}</small>
    </div>
    <div className="mv-dashboard">
      <div className="mv-top"><span>{lang==="es"?"Espacio de acompañamiento":"Mentoring space"}</span><b>{lang==="es"?"Progreso 68%":"Progress 68%"}</b></div>
      <div className="mv-hero">
        <img src="/metodo-vivo-mentoring-v12.png" alt="" aria-hidden="true"/>
        <div className="mv-hero-copy"><small>{lang==="es"?"RECORRIDO ACTIVO":"ACTIVE JOURNEY"}</small><strong>{lang==="es"?"Convertí intención en transformación.":"Turn intention into transformation."}</strong><p>{lang==="es"?"Herramientas, sesiones y evidencia de progreso en una experiencia con tu identidad.":"Tools, sessions and visible progress in an experience built around your identity."}</p><span>{lang==="es"?"Continuar recorrido →":"Continue journey →"}</span></div>
      </div>
      <div className="mv-cards"><div><small>{lang==="es"?"PRÓXIMA SESIÓN":"NEXT SESSION"}</small><strong>{lang==="es"?"Claridad para decidir":"Clarity to decide"}</strong><span>{lang==="es"?"Preparar encuentro":"Prepare session"}</span></div><div><small>{lang==="es"?"REFLEXIÓN":"REFLECTION"}</small><strong>{lang==="es"?"¿Qué cambió desde la última conversación?":"What changed since the last conversation?"}</strong><span>{lang==="es"?"Registrar avance":"Capture progress"}</span></div><div><small>{lang==="es"?"HERRAMIENTA":"TOOL"}</small><strong>{lang==="es"?"Mapa de decisiones":"Decision map"}</strong><span>{lang==="es"?"Abrir herramienta":"Open tool"}</span></div></div>
    </div>
  </figure>
}

function NarrativePortalVisual({lang}:{lang:Lang}){
  const steps=lang==="es"?["LIBRO FÍSICO","ACCESO PROTEGIDO","EXPERIENCIA DIGITAL"]:["PHYSICAL BOOK","PROTECTED ACCESS","DIGITAL EXPERIENCE"];
  return <figure className="project-visual narrative-portal-visual" aria-label={lang==="es"?"Del libro físico al portal narrativo interactivo":"From the physical book to the interactive narrative portal"}>
    <div className="np-panel np-book"><img src="/que-embole-book-cover-v14.jpeg" alt={lang==="es"?"Ejemplar físico del libro ¡Qué Embole!":"Physical copy of the book ¡Qué Embole!"}/><span><b>01</b>{steps[0]}</span></div>
    <i className="np-arrow" aria-hidden="true">→</i>
    <div className="np-panel np-access"><img src="/que-embole-portal-access-v14.jpeg" alt={lang==="es"?"Página del libro con acceso al portal de integración":"Book page containing access to an integration portal"}/><div className="qr-protection" aria-label={lang==="es"?"Código protegido":"Protected code"}><strong>MPA</strong><small>{lang==="es"?"ACCESO PROTEGIDO":"PROTECTED ACCESS"}</small></div><span><b>02</b>{steps[1]}</span></div>
    <i className="np-arrow" aria-hidden="true">→</i>
    <div className="np-panel np-portal"><img src="/que-embole-portals-v14.png" alt={lang==="es"?"Portal digital del universo ¡Qué Embole!":"Digital portal for the ¡Qué Embole! universe"}/><span><b>03</b>{steps[2]}</span></div>
  </figure>
}
